pipeline {
    agent any

    tools {
        maven 'MAVEN_3_6_3'
        jdk 'JDK_17'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Test') {
            steps {
                withMaven(maven: 'MAVEN_3_6_3',)
                {
                    // Ejecuta el test específico
                    bat 'mvn -Dtest=com.meditech.docseeker.healing.service.NewServiceImplTest#succesfullCreate test'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
