pipeline {
    agent any

    tools {
         maven 'MAVEN_3_6_3'
         jdk 'JDK_17'
    }

    stages {
         stage ('Compile Stage') {
           steps {
               withMaven(maven : 'MAVEN_3_6_3') {
                   bat 'mvn clean compile'
               }
            }
         }

        stage('Testing Stage') {
            steps {
                withMaven(maven: 'MAVEN_3_6_3',){
                    // Ejecuta el test específico
                    bat 'mvn test'
                }
            }
         }

         stage('Package Stage') {
            steps {
                withMaven(maven: 'Maven_3_9_5') {
                    // Asegúrate de también excluir el test al empaquetar si es necesario
                    bat 'mvn package -DskipTests'
                }
            }
         }
    }
}
